# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
  - name: PLUGIN_NAME # name of the parameter; required
    type: string # data type of the parameter; required
    default: in-app-browser
    values:
    - in-app-browser
    - contacts
    - calendar
    - notifications
    - location
    - one-signal
    - cipher-local-storage
    - ssl-pinning

  - name: 'MY # name of the parameter; required'
    type: string # data type of the parameter; required
    default: ${{ parameters.PLUGIN_NAME }}
    values:
    - in-app-browser
    - contacts


pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
